---
# tasks file for nodejs-servers
- name: Install nodejs
  apt:
    name:
      - nodejs
      - npm
    state: present
    update_cache: yes
  notify: Create dir app

- name: Install "express" node.js package.
  npm:
    name: express
    path: /app

- name: Copy index.js
  template:
    src: index.js.j2
    dest: /app/index.js
